notlogin=§e[fastlogin]§b你需要登录后才能操作,使用/login 密码 来登录
notregister=§e[fastlogin]§b你需要注册后才能操作,使用/register 密码 确认密码 来注册
logintimeoutkick=登录超时
repeatlogin=§e[fastlogin]§c你已经登录了!
repeatregister=§e[fastlogin]§c你已经注册了!
notregister2=§e[fastlogin]§c你还没有注册！
loginsuccessful=§e[fastlogin]§a登录成功！
passworderror=§e[fastlogin]§c密码错误！
registersuccessful=§e[fastlogin]§a注册完成！
nullpassword=§e[fastlogin]§c请输入密码！
passwdmax=§e[fastlogin]§c密码长度超过最大限制！
passwdmin=§e[fastlogin]§c密码太短！
confirmpasswd=§e[fastlogin]§c请输入确认密码 例:/register 12345 12345
confirmpasswderror=§e[fastlogin]§c两次输入的密码不一致
joingameerror1=登录失败:相同用户名的玩家已经在游戏中!
modifypwusage=§e[fastlogin]§c修改密码 - 用法:/ModifyPasswd 旧密码 新密码 确认新密码
modifyoldpwerr=§e[fastlogin]§c修改密码 - 失败:旧密码错误.
modifyconfirmerror=§e[fastlogin]§c修改密码 - 失败:两次输入的确认密码不一致.
remodifypasswd=§e[fastlogin]§c修改密码 - 失败:新密码不能和旧密码一样.
modifypasswdlengthmax=§e[fastlogin]§c修改密码 - 失败:新密码超过长度限制.
modifypasswdlengthmin=§e[fastlogin]§c修改密码 - 失败:新密码太短.
modifysuccessful=§e[fastlogin]§c修改密码 - §3成功:密码已更改！.
loginout=§e[fastlogin]§c·登录已经被注销
